# Generated by Django 4.2.7 on 2024-06-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.BigIntegerField()),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнен')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.BigIntegerField()),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('number_of_workers', models.IntegerField(default=0, verbose_name='Количество рабочих')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='telegrambot.construction')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram.', unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя в Telegram.', max_length=120, null=True, verbose_name='Фамилия')),
                ('department', models.CharField(blank=True, choices=[('contract', 'Договорной отдел'), ('project_manager', 'Руководитель проекта'), ('work', 'Бригадир'), ('director', 'Директор')], max_length=20, null=True, verbose_name='Отдел')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан пользователь.', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Underperformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('volume', 'Объем'), ('workers', 'Количество рабочих'), ('both', 'Объем и количество рабочих')], max_length=7)),
                ('deficit_volume', models.FloatField(blank=True, null=True)),
                ('deficit_workers', models.IntegerField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underperformances', to='telegrambot.stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='workers_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_stages', to='telegrambot.telegramuser'),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_objects', to='telegrambot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('number_of_workers', models.IntegerField()),
                ('completed_volume', models.FloatField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='telegrambot.stage')),
            ],
        ),
        migrations.AddField(
            model_name='construction',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='telegrambot.object'),
        ),
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to='telegrambot.stage')),
            ],
        ),
    ]
