# Generated by Django 4.2.7 on 2024-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='completed_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='underperformance',
            name='deficit_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='underperformance',
            name='reason',
            field=models.CharField(choices=[('volume', 'Объем'), ('workers', 'Количество рабочих'), ('both', 'Объем и количество рабочих')], max_length=7),
        ),
    ]
