# Generated by Django 4.2.7 on 2024-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='department',
            field=models.CharField(blank=True, choices=[('contract', 'Договорной отдел'), ('distribution', 'Отдел распределения'), ('work', 'Рабочий отдел')], max_length=20, null=True, verbose_name='Отдел'),
        ),
    ]
