# Generated by Django 4.2.7 on 2024-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_alter_completedwork_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='department',
            field=models.CharField(blank=True, choices=[('contract', 'Договорной отдел'), ('project_manager', 'Руководитель проекта'), ('work', 'Бригадир'), ('director', 'Директор')], max_length=20, null=True, verbose_name='Отдел'),
        ),
    ]
