# Generated by Django 4.2.7 on 2024-05-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_object_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to='telegrambot.telegramuser'),
        ),
    ]
