# Generated by Django 4.2.7 on 2024-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_remove_stage_assigned_worker_stage_workers_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
